/** Google Play supported languages (BCP-47 codes) */
export interface GoogleLanguage {
  code: string
  label: string
}

export const GOOGLE_LANGUAGES: GoogleLanguage[] = [
  { code: 'af', label: 'Afrikaans' },
  { code: 'sq', label: 'Albanian' },
  { code: 'am', label: 'Amharic' },
  { code: 'ar', label: 'Arabic' },
  { code: 'hy-AM', label: 'Armenian' },
  { code: 'az-AZ', label: 'Azerbaijani' },
  { code: 'bn-BD', label: 'Bangla' },
  { code: 'eu-ES', label: 'Basque' },
  { code: 'be', label: 'Belarusian' },
  { code: 'bg', label: 'Bulgarian' },
  { code: 'my-MM', label: 'Burmese' },
  { code: 'ca', label: 'Catalan' },
  { code: 'zh-HK', label: 'Chinese (Hong Kong)' },
  { code: 'zh-CN', label: 'Chinese (Simplified)' },
  { code: 'zh-TW', label: 'Chinese (Traditional)' },
  { code: 'hr', label: 'Croatian' },
  { code: 'cs-CZ', label: 'Czech' },
  { code: 'da-DK', label: 'Danish' },
  { code: 'nl-NL', label: 'Dutch' },
  { code: 'en-AU', label: 'English (Australia)' },
  { code: 'en-CA', label: 'English (Canada)' },
  { code: 'en-GB', label: 'English (United Kingdom)' },
  { code: 'en-US', label: 'English (United States)' },
  { code: 'en-IN', label: 'English (India)' },
  { code: 'en-SG', label: 'English (Singapore)' },
  { code: 'en-ZA', label: 'English (South Africa)' },
  { code: 'et', label: 'Estonian' },
  { code: 'fil', label: 'Filipino' },
  { code: 'fi-FI', label: 'Finnish' },
  { code: 'fr-CA', label: 'French (Canada)' },
  { code: 'fr-FR', label: 'French (France)' },
  { code: 'gl-ES', label: 'Galician' },
  { code: 'ka-GE', label: 'Georgian' },
  { code: 'de-DE', label: 'German' },
  { code: 'el-GR', label: 'Greek' },
  { code: 'gu', label: 'Gujarati' },
  { code: 'iw-IL', label: 'Hebrew' },
  { code: 'hi-IN', label: 'Hindi' },
  { code: 'hu-HU', label: 'Hungarian' },
  { code: 'is-IS', label: 'Icelandic' },
  { code: 'id', label: 'Indonesian' },
  { code: 'it-IT', label: 'Italian' },
  { code: 'ja-JP', label: 'Japanese' },
  { code: 'kn-IN', label: 'Kannada' },
  { code: 'kk', label: 'Kazakh' },
  { code: 'km-KH', label: 'Khmer' },
  { code: 'ko-KR', label: 'Korean' },
  { code: 'ky-KG', label: 'Kyrgyz' },
  { code: 'lo-LA', label: 'Lao' },
  { code: 'lv', label: 'Latvian' },
  { code: 'lt', label: 'Lithuanian' },
  { code: 'mk-MK', label: 'Macedonian' },
  { code: 'ms-MY', label: 'Malay (Malaysia)' },
  { code: 'ms', label: 'Malay' },
  { code: 'ml-IN', label: 'Malayalam' },
  { code: 'mr-IN', label: 'Marathi' },
  { code: 'mn-MN', label: 'Mongolian' },
  { code: 'ne-NP', label: 'Nepali' },
  { code: 'no-NO', label: 'Norwegian' },
  { code: 'fa', label: 'Persian' },
  { code: 'fa-AE', label: 'Persian (UAE)' },
  { code: 'fa-AF', label: 'Persian (Afghanistan)' },
  { code: 'fa-IR', label: 'Persian (Iran)' },
  { code: 'pl-PL', label: 'Polish' },
  { code: 'pt-BR', label: 'Portuguese (Brazil)' },
  { code: 'pt-PT', label: 'Portuguese (Portugal)' },
  { code: 'pa', label: 'Punjabi' },
  { code: 'ro', label: 'Romanian' },
  { code: 'rm', label: 'Romansh' },
  { code: 'ru-RU', label: 'Russian' },
  { code: 'sr', label: 'Serbian' },
  { code: 'si-LK', label: 'Sinhala' },
  { code: 'sk', label: 'Slovak' },
  { code: 'sl', label: 'Slovenian' },
  { code: 'es-419', label: 'Spanish (Latin America)' },
  { code: 'es-ES', label: 'Spanish (Spain)' },
  { code: 'es-US', label: 'Spanish (United States)' },
  { code: 'sw', label: 'Swahili' },
  { code: 'sv-SE', label: 'Swedish' },
  { code: 'ta-IN', label: 'Tamil' },
  { code: 'te-IN', label: 'Telugu' },
  { code: 'th', label: 'Thai' },
  { code: 'tr-TR', label: 'Turkish' },
  { code: 'uk', label: 'Ukrainian' },
  { code: 'ur', label: 'Urdu' },
  { code: 'vi', label: 'Vietnamese' },
  { code: 'zu', label: 'Zulu' }
]

export function getLanguageLabel(code: string): string {
  return GOOGLE_LANGUAGES.find((l) => l.code === code)?.label || code
}
